import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<Uint8List> generateReport(String content) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('WorkNest AI Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo)),
                  pw.Text(DateTime.now().toString().substring(0, 10), style: const pw.TextStyle(color: PdfColors.grey)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Paragraph(
              text: content,
              style: const pw.TextStyle(fontSize: 12, lineSpacing: 5),
            ),
            pw.SizedBox(height: 40),
            pw.Divider(),
            pw.Footer(
              leading: pw.Text('Generated by WorkNest AI'),
              trailing: pw.Text('Confidential'),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }
}
